### ISSUE TITLE
Generated Normals causes crash

### ISSUE THREAD

**Issue by Flare26** [gri573/rethinking-voxels#87]
Turn on "Generated Normals" , game instantly saves & exits.
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-02-28 01:42:43
Description: Unexpected error

java.lang.RuntimeException: net.minecraft.class_2973: Invalid shaders/core/clouds.json: The validated expression is false
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.reloadTextures(CloudRenderer.java:307)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.<init>(CloudRenderer.java:61)
	at net.minecraft.class_761.method_3259(class_761.java:13705)
	at net.minecraft.class_761.method_22710(class_761.java:1521)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$zmf000$redirectRenderingWorld(class_757.java:2706)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_2973: Invalid shaders/core/clouds.json: The validated expression is false
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:201)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.reloadTextures(CloudRenderer.java:305)
	... 13 more
Caused by: java.lang.IllegalArgumentException: The validated expression is false
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
	at net.minecraft.class_281.handler$zng000$onBeginCompileShaderInternal(class_281.java:540)
	at net.minecraft.class_281.method_34416(class_281.java)
	at net.minecraft.class_281.method_1283(class_281.java:51)
	at net.minecraft.class_5944.method_34579(class_5944.java:239)
	at net.minecraft.class_5944.<init>(class_5944.java:183)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.reloadTextures(CloudRenderer.java:307)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.<init>(CloudRenderer.java:61)
	at net.minecraft.class_761.method_3259(class_761.java:13705)
	at net.minecraft.class_761.method_22710(class_761.java:1521)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$zmf000$redirectRenderingWorld(class_757.java:2706)

-- Affected level --
Details:
	All players: 1 total; [class_746['xxxxxxxxx'/8932, l='ClientWorld minecraft:overworld', x=-1823.29, y=63.00, z=259.91]]
	Chunk stats: Client Chunks (ImmPtl) 162
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1836,69,656), Section: (at 4,5,0 in -115,4,41; chunk contains blocks -1840,-64,656 to -1825,319,671), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,-64,512 to -1537,319,1023)
	Level time: 57449104 game time, 2065155 day time
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1008577536 bytes (961 MiB) / 2013265920 bytes (1920 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29099.77
	Virtual memory used (MB): 17350.01
	Swap memory total (MB): 12794.06
	Swap memory used (MB): 83.75
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.69.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.19+8d1895cf85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.18+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.0+689f5e7185
			fabric-block-api-v1: Fabric Block API (v1) 1.0.3+12bfe4ea85
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.28+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.9+49abcf7e85
			fabric-command-api-v1: Fabric Command API (v1) 1.2.19+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.15+49abcf7e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.36+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.44+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.12+49abcf7e85
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.12+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.1+112a38be85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.39+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.5+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.37+422b77fb85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.39+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.28+2894d6df85
			fabric-item-api-v1: Fabric Item API (v1) 2.1.5+4d2c606385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.8+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.28+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.26+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.8+2894d6df85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.18+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.22+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.12+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.29+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.25+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.14+d9ac3c3985
			fabric-networking-v0: Fabric Networking (v0) 0.3.31+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.0+e9dee00485
			fabric-particles-v1: Fabric Particles (v1) 1.0.18+fbde993d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.1+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.0+2063beff85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.23+11ba9c3b85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.28+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.23+48349a3f85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.16+3067f46385
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.31+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.7+49abcf7e85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.0+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.3+a10d22bd85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.39+1d4d0b5785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.10+689f5e7185
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.6+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.12+82a2701785
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.1.0+0efcd39b85
		fabricloader: Fabric Loader 0.14.12
		immersive_portals: Immersive Portals 2.4.8
			cloth-config: Cloth Config v9 9.0.94
				cloth-basic-math: cloth-basic-math 0.6.1
			imm_ptl_core: Immersive Portals Core 2.4.8
			q_misc_util: QMiscUtil 2.4.8
		iris: Iris 1.5.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
		sodium: Sodium 0.4.8+build.22
		vivecraft: Vivecraft 1.19.3-0.0.13
	Loaded Shaderpack: rethinking-voxels (fallback)
		Profile: Custom (+18 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.12-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.49, NVIDIA Corporation
	Window size: 1280x720
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor

**Comment by gri573** [comment]
this is probably a problem with sodium, as the shader doesn't even use gbuffers_clouds

**Comment by gri573** [comment]
you could try the latest commit, it fixes a compile error with generated normals
